"""SDK non ufficiale per Normattiva, il portale della legge vigente."""

from normattiva import codici
from normattiva.codici import AttoNoto
from normattiva.errori import (
    AmbiguityError,
    ConnectionError,
    ExportFailedError,
    InvalidArgumentError,
    InvalidUrnError,
    NormattivaError,
    NotFoundError,
    NotYetInForceError,
    OverloadedError,
    RequestBlockedError,
    RuleCode,
    RuleViolationError,
    TooManyResultsError,
    TruncationError,
    UnexpectedResponseError,
    ValidityMismatchError,
    VersionNotFoundError,
)
from normattiva.modelli import (
    ABBREVIAZIONI,
    ARTICOLO,
    ATTRIBUZIONE,
    DENOMINAZIONI_URN,
    Aggiornamento,
    AttoStorico,
    AttoTrovato,
    ClasseProvvedimento,
    Collection,
    Comma,
    DettaglioAtto,
    EsitoRicerca,
    EstremiAtto,
    Evidenziazione,
    ExportMode,
    Faccetta,
    Faccette,
    FinestraVigenza,
    Format,
    Partizione,
    PubblicazioneGazzetta,
    RicercaPredefinita,
    RiferimentoAggiornamento,
    Sort,
    Tipologica,
    VersioneAtto,
)
from normattiva.testo import normalize_accents
from normattiva.urn import Urn

__version__ = "0.1.0"

__all__ = [
    "ABBREVIAZIONI",
    "ARTICOLO",
    "ATTRIBUZIONE",
    "DENOMINAZIONI_URN",
    "Aggiornamento",
    "AmbiguityError",
    "AttoNoto",
    "AttoStorico",
    "AttoTrovato",
    "ClasseProvvedimento",
    "Collection",
    "Comma",
    "ConnectionError",
    "DettaglioAtto",
    "EsitoRicerca",
    "EstremiAtto",
    "Evidenziazione",
    "ExportFailedError",
    "ExportMode",
    "Faccetta",
    "Faccette",
    "FinestraVigenza",
    "Format",
    "InvalidArgumentError",
    "InvalidUrnError",
    "NormattivaError",
    "NotFoundError",
    "NotYetInForceError",
    "OverloadedError",
    "Partizione",
    "PubblicazioneGazzetta",
    "RequestBlockedError",
    "RicercaPredefinita",
    "RiferimentoAggiornamento",
    "RuleCode",
    "RuleViolationError",
    "Sort",
    "Tipologica",
    "TooManyResultsError",
    "TruncationError",
    "UnexpectedResponseError",
    "Urn",
    "ValidityMismatchError",
    "VersionNotFoundError",
    "VersioneAtto",
    "__version__",
    "codici",
    "normalize_accents",
]
